---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: openshift/production
          role: hahl-ocp-prod
          serviceAccountRef:
            name: vault-auth
            namespace: default
      path: hahl-ocp-prod-kv
      server: 'https://vault.hahl.au'
      version: v2

