apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: operators
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cert-manager/cloudflare-api-token
        property: key
      secretKey: key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-api-token
    template:
      data:
        api-token: '{{.key}}'
      engineVersion: v2
      type: Opaque
