apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-zerossl-eab
  namespace: operators
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cert-manager/zerossl-eab
        property: key
      secretKey: key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: zerossl-eab
    template:
      data:
        secret: '{{.key}}'
      engineVersion: v2
      type: Opaque
