---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: operators
  name: zerossl
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: 4nZV_HGU6DJVPTuKmxmeiw
      keySecretRef:
        name: zerossl-eab
        key: secret
    privateKeySecretRef:
      name: zerossl-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
